language: ruby
before_script:
  - psql -c 'create database "AppDojo-API_test";' -U postgres
rvm:
  - 2.0.0
notifications:
  email: false
  campfire:
    rooms:
      secure: CPyksUcwLPYlzvmzYV1wlPe4TRZbK0UsfZ7d+TrkFP1Sl4M4KVWI/PULVCJenWWW+Ye2LRAWCi4SjDkMxFtiRQVfPTsjaNiQp56qCXR5EPOzqecNNPvaffVAs8H5P6sEXu+8Voq1Q2sNJyHcvnHYePHX1IjwQbwlrTPmQ7eUGw4=
